name: Update Minecraft Server

on:
  schedule:
    - cron: '0 0 * * *' # Daily check
  workflow_dispatch:

jobs:
  update-server:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
      
    - name: Download latest Minecraft server
      run: |
        curl -o server.jar https://launcher.mojang.com/v1/objects/[LATEST-1.21.5-HASH]/server.jar
        # Replace [LATEST-1.21.5-HASH] with actual hash when available
        
    - name: Commit and push if changed
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        git add server.jar
        git diff --quiet && git diff --staged --quiet || git commit -m "Update server.jar"
        git push
